### ISSUE TITLE
[DEVICE]: Preventing state update

### ISSUE THREAD

**Issue by gamajunior** [ale-jr/rinnai_br_homeassistant#10]
A cerca de uma semana o ADDON começou a se portar estranho e olhando o log ele exibe essa mensagem [DEVICE]: Preventing state update.

Usando os comandos o aquecedor está retornando essas infos
http://192.168.1.210/bus
41,0,0,33800,1227,14364,10000,0,0,0,2500,2628,0,330,260,3700,192.168.1.210,192.168.1.100:pri,5,21216245,497,0,Sep 16 2022,0,Software/System restart,50:02:91:db:b6:4a,0,0,26,0,0,0,0,0,0,0,0,-84,[0],0

http://192.168.1.210/tela_
41,0,0,1227,14364,0,192.168.1.100:pri,5,550,Sep 16 2022,0,0,0,0

http://192.168.1.210/inc
41,0,0,1227,14364,0,192.168.1.100:pri,5,640,Sep 16 2022,0,0,0,0

http://192.168.1.210/dec
41,0,0,1227,14364,0,192.168.1.100:pri,4,682,Sep 16 2022,0,0,0,0

http://192.168.1.210/consumo
18:40,126,1511,0:0,0,0

http://192.168.1.210/historico
1:20,4,8,76,1681596793;3:18,4,21,204,1681596527;6:03,7,41,608,1681582256;2:02,7,13,178,1681581671;2:38,7,23,346,1681569617;1:18,7,25,249,1681569239;16:02,7,274,3998,1681564583;1:23,7,4,12,1681558608;1:12,7,6,75,1681558422;8:43,7,128,1906,1681552569;

http://192.168.1.210/erros
2,1674045534;10,1668165401;10,1668165205;10,1668165020;10,1668138715;10,1663943891;10,1668135352;10,1668118302;10,1668118045;10,1668087273;

Abaixo o log completo:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Hello world!
> modulo_aquecedor_rinnai_brasil@1.2.1 start
> NODE_ENV=production node src/main.js
[RINNAI API] set priority to null
[MQTT] Connected
[MQTT] subscribed to set water target temp topic
[MQTT] subscribed to switch heater topic
[MQTT] subscribed to increase temperature topic
[MQTT] subscribed to decrease temperature topic
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] set priority to 192.168.1.100
[RINNAI API] set priority to null
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] set priority to 192.168.1.100
[RINNAI API] fetching heater parameters
[RINNAI API] set priority to null
[RINNAI API] set priority to 192.168.1.100
[RINNAI API] set priority to null
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] fetching heater parameters
[RINNAI API] fetching heater state
[RINNAI API] set priority to 192.168.1.100
[RINNAI API] fetching heater state
[RINNAI API] set priority to 192.168.1.100
[RINNAI API] fetching heater state
[RINNAI API] set priority to 192.168.1.100
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update
[DEVICE]: Preventing state update

**Comment by tegots123** [comment]
Conseguiu alguma solução ? Aqui tbm passou a apresentar o mesmo problema

**Comment by gamajunior** [comment]
Consegui sim, resetei o app no smartphone e refiz a configuração, depois disso parou o erro, pelo menos por enquanto.
