### ISSUE TITLE
HA Sem Supervisor

### ISSUE THREAD

**Issue by davidalben** [ale-jr/rinnai_br_homeassistant#2]
Ale, parabéns! O pessoal do grupo de HA Brasil que está querendo um aquecedor novo agora vai dar preferência para a Rinnai, com certeza!

Eu tinha decifrado alguns desses valores, mas estava usando tudo por REST.
Uma dúvida: minha instalação é sem Supervisor. Tem como instalar seu add-on nela?
Grato!

**Comment by ale-jr** [comment]
Opa, tudo bem? 
Infelizmente só dá para instalar se tiver o supervisor :/ queria fazer criar uma integração própria para o HA sem precisar do addon assim funcionaria em qualquer instalação do HA mas meus skills em python ainda não são dos melhores, quem sabe um dia :sweat_smile:  kkkkkk
Mas seria possível rodar o projeto fora do HA em um container docker ou rodando diretamente o script em uma máquina com node instalado desde que tenha acesso ao broker do mqtt, se quiser testar é só subir o [projeto em modo de desenvolvimento](https://github.com/ale-jr/rinnai_br_homeassistant#iniciar-o-projeto-localmente-em-modo-de-desenvolvimento) em um ambiente que tenha node instalado assim que subir o projeto com o `npm start` o home assistant vai criar e atualizar as entidades
